pipeline {
 agent any
 stages {
 stage('Setup Maven') {
 steps {
 sh '''
 if [ ! -d maven ]; then
 curl -s https://downloads.apache.org/maven/maven3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz | tar xz
 mv apache-maven-3.9.9 maven
 fi
 '''
 }
 }
 stage('Build') {
 steps {
 sh './maven/bin/mvn clean install'
 }
 }
 }
 }
