 pipeline {
  agent any
stages {
 stage('Build with custom Maven') {
 steps {
 sh '''
 curl -s https://downloads.apache.org/maven/maven3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz | tar xz
 ./apache-maven-3.9.9/bin/mvn clean install
 '''
 }
 }
 }
 }
